server:
  port: 9528
  servlet:
    context-path: /hmhw
  tomcat:
    uri-encoding: UTF-8
    redirect-context-root: false
    use-relative-redirects: false

spring:
  application:
    name: hmhw-service
  servlet:
    multipart:
      max-file-size: 500MB      #设置上传单个文件的大小
      max-request-size: 500MB   #设置单次请求的文件的总大小
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
    initialSize: 5
    minIdle: 5
    maxActive: 20

# mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.weibo.project.hmhw.model

# mybatis-plus 配置
mybatis-plus:
  configuration:
    jdbc-type-for-null: "null"   #注意：单引号
    cache-enabled: false
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除配置
    id-type: 0
